#VRMS Email Config
#Sat Jul 18 21:08:02 EEST 2026
mail.enabled=true
mail.from=kingziad924@gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.host=smtp.gmail.com
mail.subject.prefix=[VRMS]
mail.username=kingziad924@gmail.com
